### ISSUE TITLE
FOLIO Workflow for MSL GPS access - not including some patrons

### ISSUE THREAD

**Issue by jeremythuff** [TAMULib/fw-registry#279]
From KACE: https://k1000.library.tamu.edu/userui/ticket.php?ID=56539

Robin Sewell

What app(s) were you in?:

What is the issue? FOLIO Workflow for MSL GPS access - not including some patrons
What was expected to happen? The MSL GPS Zone Authorization LIst Workflow is not including the Health & Kinesiology grad students
Is there a work around to the issue? Yes
If there is a workaround, briefly describe. Yes, but it involves me manually adding each credential into Frontier once for mag strip and once for the card chip.
What is the impact on your ability to do your job? 4
Where are you? On campus - College Station
Are you on wifi? No

**Comment by rmathew1011** [comment]
While generating  report - the message says "Report has been successfully generated"
but when looking into the workflow incident history 
_HTTP error retrieving workflow data: HTTP/1.1 500_

**Comment by rmathew1011** [comment]
Error from mod-camunda-logs:
: ```
Correlating message /events/workflow/medsci-gps-zone/start
2023-03-03 15:30:52.980 ERROR 6 --- [ntContainer#0-1] org.camunda.bpm.engine.context           : ENGINE-16004 Exception while closing command context: Cannot correlate message '/events/workflow/medsci-gps-zone/start': No process definition matches the parameters
org.camunda.bpm.engine.MismatchingMessageCorrelationException: Cannot correlate message '/events/workflow/medsci-gps-zone/start': No process definition matches the parameters
	at org.camunda.bpm.engine.impl.cmd.CorrelateMessageCmd.execute(CorrelateMessageCmd.java:74) ~[camunda-engine-7.17.0.jar!/:7.17.0]
	at org.camunda.bpm.engine.impl.cmd.CorrelateMessageCmd.execute(CorrelateMessageCmd.java:42) ~[camunda-engine-7.17.0.jar!/:7.17.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:28) ~[camunda-engine-7.17.0.jar!/:7.17.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:110) ~[camunda-engine-7.17.0.jar!/:7.17.0]
	at org.camunda.bpm.engine.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:72) ~[camunda-engine-spring-7.17.0.jar!/:7.17.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.19.jar!/:5.3.19]
	at org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:70) ~[camunda-engine-spring-7.17.0.jar!/:7.17.0]
	at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70) ~[camunda-engine-7.17.0.jar!/:7.17.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandCounterInterceptor.execute(CommandCounterInterceptor.java:35) ~[camunda-engine-7.17.0.jar!/:7.17.0]
	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33) ~[camunda-engine-7.17.0.jar!/:7.17.0]
	at org.camunda.bpm.engine.impl.MessageCorrelationBuilderImpl.execute(MessageCorrelationBuilderImpl.java:322) ~[camunda-engine-7.17.0.jar!/:7.17.0]
	at org.camunda.bpm.engine.impl.MessageCorrelationBuilderImpl.correlateWithResult(MessageCorrelationBuilderImpl.java:233) ~[camunda-engine-7.17.0.jar!/:7.17.0]
	at org.camunda.bpm.engine.impl.MessageCorrelationBuilderImpl.correlateStartMessage(MessageCorrelationBuilderImpl.java:292) ~[camunda-engine-7.17.0.jar!/:7.17.0]
	at org.folio.rest.jms.EventConsumer.receive(EventConsumer.java:51) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.19.jar!/:5.3.19]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.19.jar!/:5.3.19]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.3.19.jar!/:5.3.19]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.3.19.jar!/:5.3.19]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.3.19.jar!/:5.3.19]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.3.19.jar!/:5.3.19]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.19.jar!/:5.3.19]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:331) ~[spring-jms-5.3.19.jar!/:5.3.19]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:270) ~[spring-jms-5.3.19.jar!/:5.3.19]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.19.jar!/:5.3.19]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.19.jar!/:5.3.19]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.19.jar!/:5.3.19]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```
